#!/bin/bash
openstack project create --description "Kubernetes on Openstack: Lab-01" kube-os-lab-01
openstack project create --description "Kubernetes on Openstack: Lab-02" kube-os-lab-02
openstack project create --description "Kubernetes on Openstack: Lab-03" kube-os-lab-03
openstack project create --description "Kubernetes on Openstack: Lab-04" kube-os-lab-04
openstack project create --description "Kubernetes on Openstack: Lab-05" kube-os-lab-05
openstack project create --description "Kubernetes on Openstack: Lab-06" kube-os-lab-06
openstack project create --description "Kubernetes on Openstack: Lab-07" kube-os-lab-07
openstack project create --description "Kubernetes on Openstack: Lab-08" kube-os-lab-08
openstack project create --description "Kubernetes on Openstack: Lab-09" kube-os-lab-09
openstack project create --description "Kubernetes on Openstack: Lab-10" kube-os-lab-10
openstack project create --description "Kubernetes on Openstack: Lab-11" kube-os-lab-11
openstack project create --description "Kubernetes on Openstack: Lab-12" kube-os-lab-12
openstack project create --description "Kubernetes on Openstack: Lab-13" kube-os-lab-13
openstack project create --description "Kubernetes on Openstack: Lab-14" kube-os-lab-14
openstack project create --description "Kubernetes on Openstack: Lab-15" kube-os-lab-15
openstack project create --description "Kubernetes on Openstack: Lab-16" kube-os-lab-16
openstack project create --description "Kubernetes on Openstack: Lab-17" kube-os-lab-17
openstack project create --description "Kubernetes on Openstack: Lab-18" kube-os-lab-18
openstack project create --description "Kubernetes on Openstack: Lab-19" kube-os-lab-19
openstack project create --description "Kubernetes on Openstack: Lab-20" kube-os-lab-20
openstack project create --description "Kubernetes on Openstack: Lab-21" kube-os-lab-21
openstack project create --description "Kubernetes on Openstack: Lab-22" kube-os-lab-22
openstack project create --description "Kubernetes on Openstack: Lab-23" kube-os-lab-23
openstack project create --description "Kubernetes on Openstack: Lab-24" kube-os-lab-24
openstack project create --description "Kubernetes on Openstack: Lab-25" kube-os-lab-25
